[package]
name = "valve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extendr-api = "0.4.0"
extendr-engine = "0.4.0"
reqwest = { version = "0.11.18", features = ["blocking"] }
