[package]
name = "valve"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = [ "cdylib",  "staticlib"]

[registries.crates-io]
protocol = "sparse"

[dependencies]
argh = "0.1.10"
axum = { version = "*" }
extendr-engine = "0.4.0"
hyper = "0.14.26"
rand = "0.8.5"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread", "signal"] }
extendr-api = '*'




