# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_valve_wrappers", use_symbols = TRUE, package_name = "valve")

#' @docType package
#' @usage NULL
#' @useDynLib valve, .registration = TRUE
NULL

valve_run_ <- function(filepath, host, port, workers, n_min, n_max, check_interval, max_age) invisible(.Call(wrap__valve_run_, filepath, host, port, workers, n_min, n_max, check_interval, max_age))


# nolint end
