# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_valve_wrappers", use_symbols = TRUE, package_name = "valve")

#' @docType package
#' @usage NULL
#' @useDynLib valve, .registration = TRUE
NULL

valve_run_ <- function(filepath, host, port, n_threads, workers) invisible(.Call(wrap__valve_run_, filepath, host, port, n_threads, workers))


# nolint end
